### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by sah-anshu** [tessercat/pbx-web#2]
Hi
I am noob to Freeswitch, basically migrating myself from asterisk to FreeSWITCH, 
can you please help me with the documentation to implement your project.

Thanks in advance
Anshu

**Comment by tessercat** [comment]
Hi Anshu, you can find design docs in the pbx-docs repo, but not installation docs. Note that this is a hobby project, and not open source.

FreeSWITCH is extremely flexible, but has a huge learning curve. If you intend to build a custom application, my advice would be to install it on a Debian 11 host as described in the [FreeSWITCH project's installation docs](https://freeswitch.org/confluence/display/FREESWITCH/Debian+10+Buster). (Note that the docs are for Debian 10, but FS now supports Debian 11, and project docs have not been updated.)

FreeSWITCH is basically a module system configured in XML. Once you've installed it, take a look in /etc/freeswitch and start by reading freeswitch.xml and try to understand the configuration language from there.

If you just want a working PBX, [FusionPBX](https://www.fusionpbx.com/) is the de-facto web GUI and configuration server, and a much better option than this hobby project.
